name: test

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - dev

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        rust_version: [stable]
        platform:
          - { target: x86_64-unknown-linux-gnu, os: ubuntu-latest, kind: bench }

    runs-on: ${{ matrix.platform.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: install stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.platform.target }}

      - name: install xvfb and hyperfine (bench only)
        if: matrix.platform.kind == 'bench'
        run: |
          sudo apt-get install -y xvfb
          wget https://github.com/sharkdp/hyperfine/releases/download/v1.11.0/hyperfine_1.11.0_amd64.deb
          sudo dpkg -i hyperfine_1.11.0_amd64.deb

      - name: build electron hello_world
        if: matrix.platform.kind == 'bench'
        run: |
          cd apps/hello_world
          yarn && yarn package

      - name: build electron cpu_intensive
        if: matrix.platform.kind == 'bench'
        run: |
          cd apps/cpu_intensive
          yarn && yarn package

      - name: build electron file_transfer
        if: matrix.platform.kind == 'bench'
        run: |
          cd apps/file_transfer
          yarn && yarn package

      - name: build benchmarks
        if: matrix.platform.kind == 'bench'
        run: |
          xvfb-run --auto-servernum cargo bench

      - name: clone current benchmarks
        uses: actions/checkout@v2
        if: matrix.platform.kind == 'bench'
        with:
          token: ${{ secrets.BENCH_PAT }}
          path: gh-pages
          repository: tauri-apps/benchmark_results

      - name: post benchmarks
        if: matrix.platform.kind == 'bench'
        run: |
          cargo run --manifest-path ./bench/tools/Cargo.toml --bin build_benchmark_jsons
          cd gh-pages
          git pull
          git config user.name "tauri-bench"
          git config user.email "gh.tauribot@gmail.com"
          git add .
          git commit --message "Update benchmarks"
          git push origin gh-pages

      - name: Worker info
        if: matrix.kind == 'bench'
        run: |
          cat /proc/cpuinfo
          cat /proc/meminfo
